# Generated by Django 3.2.4 on 2021-07-26 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='permission',
            new_name='is_staff',
        ),
    ]
