# Generated by Django 3.2.4 on 2021-08-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210726_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(default=False, max_length=30, verbose_name='소셜'),
        ),
    ]
